import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Turn-To",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <iframe
          className=" top-0 left-0 right-0 w-screen h-screen border-0 z-0 scrollhide fixed"
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3672.675015531212!2d72.53763867539352!3d22.26920688528807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395e86e5b17a7fbb%3A0x858f4d37bbff5d3e!2sRajkot%2C%20Gujarat%20360001!5e0!3m2!1sen!2sin!4v1677046533035!5m2!1sen!2sin"
          allowFullScreen={true}

        />
        {children}
      </body>
    </html>
  );
}
