// app/layout.tsx (or .tsx)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from 'next/dynamic';
import "./globals.css";
import SimpleMap from "./components/Googlemap/SimpleMap";

const inter = Inter({ subsets: ["latin"] });

// Dynamically import GoogleMapComponent with no SSR

export const metadata: Metadata = {
  title: "Turn-To",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
